// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WarbandServer.Services;

#nullable disable

namespace WarbandServer.Migrations
{
    [DbContext(typeof(WarbandContext))]
    partial class WarbandContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WarbandServer.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Joined")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Pass")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("PrivateUser")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Joined = new DateTime(2023, 2, 22, 13, 13, 10, 355, DateTimeKind.Utc).AddTicks(7687),
                            Mail = "testmail1.com",
                            Name = "Test User 1",
                            Pass = "Non-hashed-password1",
                            PrivateUser = false
                        },
                        new
                        {
                            Id = 2,
                            Joined = new DateTime(2023, 2, 22, 13, 13, 10, 355, DateTimeKind.Utc).AddTicks(7690),
                            Mail = "testmail2.com",
                            Name = "Test User 2",
                            Pass = "Non-hashed-password2",
                            PrivateUser = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
